apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-data-cast
  name: postgres-data-cast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
